### ISSUE TITLE
Package failure - FileNotFoundException?

### ISSUE THREAD

**Issue by craigagnew** [HedgehogDevelopment/SitecorePackageDeployer#16]
Hey,

Has anyone encountered an issue where the items are installed but SPD reports a failure in the JSON because the Post step execution failed due to a FileNotFoundException? 

Seems to be looking for the .update file in the Post step but it's already been or is being removed?

```

Post step execution failed
	System.Exception: Error while opening file 'D:\_resources\ClientProject\Deployments\Automation\websites\clientproject\DEV\1.1.0\sitecore_packages\4_ClientProject.TDS.Master.Media_20171018_1123.update' ---> System.IO.FileNotFoundException: Could not find file 'D:\_resources\ClientProject\Deployments\Automation\websites\clientproject\DEV\1.1.0\sitecore_packages\4_ClientProject.TDS.Master.Media_20171018_1123.update'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Sitecore.Zip.ZipReader..ctor(String filename, Encoding encoding)
   --- End of inner exception stack trace ---
   at Sitecore.Zip.ZipReader..ctor(String filename, Encoding encoding)
   at Sitecore.Install.Zip.PackageReader.Populate(ISink`1 sink)
   at Sitecore.Update.UpdateHelper.LoadMetadata(String packagePath)
   at Hhogdev.SitecorePackageDeployer.Tasks.InstallPackage.ExecutePostSteps(InstallLogger installLogger, PostStepDetails postStepDetails) in C:\Git\SitecorePackageDeployer\SitecorePackageDeployer\Tasks\InstallPackage.cs:line 373
Package install failed
	System.Exception: Error while opening file 'D:\_resources\ClientProject\Deployments\Automation\websites\clientproject\DEV\1.1.0\sitecore_packages\4_ClientProject.TDS.Master.Media_20171018_1123.update' ---> System.IO.FileNotFoundException: Could not find file 'D:\_resources\ClientProject\Deployments\Automation\websites\clientproject\DEV\1.1.0\sitecore_packages\4_ClientProject.TDS.Master.Media_20171018_1123.update'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Sitecore.Zip.ZipReader..ctor(String filename, Encoding encoding)
   --- End of inner exception stack trace ---
   at Sitecore.Zip.ZipReader..ctor(String filename, Encoding encoding)
   at Sitecore.Install.Zip.PackageReader.Populate(ISink`1 sink)
   at Sitecore.Update.UpdateHelper.LoadMetadata(String packagePath)
   at Hhogdev.SitecorePackageDeployer.Tasks.InstallPackage.ExecutePostSteps(InstallLogger installLogger, PostStepDetails postStepDetails) in C:\Git\SitecorePackageDeployer\SitecorePackageDeployer\Tasks\InstallPackage.cs:line 394
   at Hhogdev.SitecorePackageDeployer.Tasks.InstallPackage.InstallPackages() in C:\Git\SitecorePackageDeployer\SitecorePackageDeployer\Tasks\InstallPackage.cs:line 198

```

**Comment by cturano** [comment]
Hi Craig,
    One possible cause of this in the 1.8 version of the SPD because the post steps were processed twice. Another cause is using the ?force=1 to install if SPD isn't locked in the installing state. Essentially, this is caused by the same package being installed multiple times simultaneously. One install finishes before the other and cleans up after itself, causing the second one to throw a FileNotFound. Please take a look in the logs and see if there are multiple installations of the file.

Thanks

Charlie

**Comment by peplau** [comment]
We are having this very ofter now, and this is very random. I would say 50% of the times it gives this error and 50% it succeeds.

A JSON with failure message appears and the package is renamed to NXA.TDS.Master.update.error_20180430.081406

Any advice?

18584 20:14:26 ERROR Installation Failed: NXA.TDS.Master.update
Exception: System.Reflection.TargetInvocationException
Message: Exception has been thrown by the target of an invocation.
Source: mscorlib
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at Hhogdev.SitecorePackageDeployer.Tasks.InstallPackage.InstallPackages() in C:\Git\SitecorePackageDeployer\SitecorePackageDeployer\Tasks\InstallPackage.cs:line 175

Nested Exception

Exception: Sitecore.Update.Installer.Exceptions.CriticalInstallationException
Message: Critical installation exception occurred.
Source: Sitecore.Update
   at Sitecore.Update.Installer.DiffInstaller.InstallPackage(String path, InstallMode mode, ProcessingMode processingMode, IProcessingContext context, Boolean& hasPostAction, String& historyPath)
   at Sitecore.Update.UpdateHelper.Install(PackageInstallationInfo info, ILog installationProcessLogger, String& historyPath)

Nested Exception

Exception: System.ArgumentOutOfRangeException
Message: Index and count must refer to a location within the buffer.
Parameter name: chars
Source: mscorlib
   at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Sitecore.Update.Installer.StreamPackageWriter.Finish()
   at Sitecore.Update.Installer.CommandInstallerContext.Dispose()
   at Sitecore.Update.Installer.DiffInstaller.InstallPackage(String path, InstallMode mode, ProcessingMode processingMode, IProcessingContext context, Boolean& hasPostAction, String& historyPath)



18584 20:14:26 FATAL Package install failed
Exception: System.Reflection.TargetInvocationException
Message: Exception has been thrown by the target of an invocation.
Source: mscorlib
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at Hhogdev.SitecorePackageDeployer.Tasks.InstallPackage.InstallPackages() in C:\Git\SitecorePackageDeployer\SitecorePackageDeployer\Tasks\InstallPackage.cs:line 175

Nested Exception

Exception: Sitecore.Update.Installer.Exceptions.CriticalInstallationException
Message: Critical installation exception occurred.
Source: Sitecore.Update
   at Sitecore.Update.Installer.DiffInstaller.InstallPackage(String path, InstallMode mode, ProcessingMode processingMode, IProcessingContext context, Boolean& hasPostAction, String& historyPath)
   at Sitecore.Update.UpdateHelper.Install(PackageInstallationInfo info, ILog installationProcessLogger, String& historyPath)

Nested Exception

Exception: System.ArgumentOutOfRangeException
Message: Index and count must refer to a location within the buffer.
Parameter name: chars
Source: mscorlib
   at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Sitecore.Update.Installer.StreamPackageWriter.Finish()
   at Sitecore.Update.Installer.CommandInstallerContext.Dispose()
   at Sitecore.Update.Installer.DiffInstaller.InstallPackage(String path, InstallMode mode, ProcessingMode processingMode, IProcessingContext context, Boolean& hasPostAction, String& historyPath)



18584 20:14:26 INFO  Setting installer state to Ready
14248 20:14:26 ERROR Error moving broken package
Exception: System.IO.FileNotFoundException
Message: Could not find file 'C:\inetpub\wwwroot\TriHealth-qa-cm.nishtechinc.com\1.0.0-beta.72\App_Data\SitecorePackageDeployer\NXA.TDS.Master.update'.
Source: mscorlib
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Hhogdev.SitecorePackageDeployer.Tasks.InstallPackage.<>c__DisplayClass20_0.<InstallPackages>b__1(Object ctx) in C:\Git\SitecorePackageDeployer\SitecorePackageDeployer\Tasks\InstallPackage.cs:line 238

**Comment by cturano** [comment]
Hi Rodrigo,
    We saw in an issue in some older versions where the package installer was multiple instances simultaneously. When that happened, the first instance finished and the second instance failed when the .update package was copied out of the folder during the install. Can you see if this is happening?

Thanks

Charlie

**Comment by peplau** [comment]
It makes sense, however apparently our CI is only calling it once, and like I said the error is not consistent. I will double check the whole CI steps and see if there's anything I can find.

This error also manifests when you are not using CI to trigger it. If you simple restart IIS then run ?force=1 you will also have this error sometimes. Do you think the simple fact of having people accessing Sitecore while the installation is executing can trigger it multiple times?

**Comment by cturano** [comment]
Hi Rodrigo,
    This was occurring at a restart of the server, where it would pickup the package in the folder and start even if it was running. You will have to review the logs and see if two installs were happening at the same time. Can you check the version of the deployer you are using? The latest should be better about not doing this.

Thanks

Charlie

**Comment by peplau** [comment]
You are right, there are two entries like that at the SAME log file:

5716 20:35:44 INFO  Begin Installation: NXA.TDS.Master.update
6044 20:36:45 INFO  Begin Installation: NXA.TDS.Master.update

Sitecore has not created now log files, which suggests IIS has not restarted.  

We are using 1.10.0.0 - a recent version which should have better handling for that. Would you know what could be causing that? In addition, what info may I provide to help you help me?

**Comment by cturano** [comment]
Hi Rodrigo,
    Can you tell me if your build process is using force=1 on the url to start the process? If so, then this is the problem. Force should only be used if you are sure an install isn't running.

Thanks

Charlie

**Comment by peplau** [comment]
Hello Charlie,

Happened that we were passing force=1 to that when we should not. I will keep you informed if that issue occurs again. For now, it looks to be working perfectly! Thank you very much for your help.

**Comment by cturano** [comment]
Excellent! Thanks!
