### ISSUE TITLE
Method not found: Void Sitecore.Update.Installer.XmlEntrySerializer.Serialize

### ISSUE THREAD

**Issue by bunny-lajolla** [HedgehogDevelopment/SitecorePackageDeployer#27]
Hi, 

I'm trying to get the package deployer working on my dev machine, but I'm running into this error and can't understand why.  The stack dump below suggests that the method doesn't exist in the Sitecore.Update library, but looking at that dll in VS object viewer (and IL DASM) suggests it **does** exist. 

I'm guessing I may have the wrong version of a dll perhaps, but can anybody point me in the right direction?
Versions:
Sitecore.NET 9.0.2 (rev. 180604)
TDS 5.7.0.27
SitecorePackageDeployer - v1.3 was installed via the Update wizard

Many thanks!

--- Begin Log file ---
ManagedPoolThread #2 12:17:21 INFO  Job started: Hhogdev.SitecorePackageDeployer.Tasks.InstallPackage
ManagedPoolThread #2 12:17:21 INFO  Committing files.
ManagedPoolThread #2 12:17:27 INFO  Executing Post Installation instructions: 'HedgehogDevelopment.SitecoreProject.PackageInstallPostProcessor.DoPostDeployActions,HedgehogDevelopment.SitecoreProject.PackageInstallPostProcessor.dll'
ManagedPoolThread #2 12:17:27 INFO  04/08/2021-12:17:27: Starting PostDeployActions. Using assembly version 5.7.0.27
ManagedPoolThread #2 12:17:27 INFO  04/08/2021-12:17:27: Recursive deploy action is set to ignore
ManagedPoolThread #2 12:17:27 WARN  All caches have been cleared. This can decrease performance considerably. DEBUG entries have to be enabled in log4net to see the corresponding stack trace.
ManagedPoolThread #2 12:17:27 INFO  04/08/2021-12:17:27: TDS PostDeployActions complete.
ManagedPoolThread #2 12:17:27 ERROR Exception
Exception: System.Reflection.TargetInvocationException
Message: Exception has been thrown by the target of an invocation.
Source: mscorlib
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Sitecore.Reflection.ReflectionUtil.InvokeMethod(MethodInfo method, Object[] parameters, Object obj)
   at Sitecore.Jobs.JobRunner.RunMethod(JobArgs args)
   at (Object , Object )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
   at Sitecore.Jobs.Job.DoExecute()
   at Sitecore.Jobs.Job.ThreadEntry(Object state)

Nested Exception

**Exception: System.MissingMethodException
Message: Method not found: 'Void Sitecore.Update.Installer.XmlEntrySerializer.Serialize(System.Collections.Generic.List`1<Sitecore.Update.Installer.ContingencyEntry>, System.IO.Stream)'.**
Source: Hhogdev.SitecorePackageDeployer
   at Hhogdev.SitecorePackageDeployer.Tasks.InstallPackage.SaveInstallationMessages(String installationHistoryRoot, List`1 logMessages)
   at Hhogdev.SitecorePackageDeployer.Tasks.InstallPackage.InstallPackages() in C:\Git\SitecorePackageDeployer\SitecorePackageDeployer\Tasks\InstallPackage.cs:line 197
   at Hhogdev.SitecorePackageDeployer.Tasks.InstallPackage.Run() in C:\Git\SitecorePackageDeployer\SitecorePackageDeployer\Tasks\InstallPackage.cs:line 69

--- End Log file ---

**Comment by nsgocev** [comment]
Sitecore Package Deployer 1.3 is not compatible with Sitecore 9.X. 

You should get version 1.10 or higher. I would recommend getting v1.11 from here: https://github.com/HedgehogDevelopment/SitecorePackageDeployer/releases

**Comment by bunny-lajolla** [comment]
Thanks for the reply, I will give that a go

**Comment by bunny-lajolla** [comment]
Thanks, that has resolved this issue, will close it off
